### ISSUE TITLE
ToggleSwitch

### ISSUE THREAD

**Issue by simurai** [montagejs/matte#15]
Currently Matte still has the [Bluemoon Toggle](https://github.com/montagejs/bluemoon/tree/master/ui/toggle.reel), so I restyled it to be more consistant with the rest of Matte.

Before submitting a pull request, the JS part still needs to be done. I'm just [toggling the CSS class](https://github.com/simurai/matte/blob/toggle-switch/ui/toggle-switch.reel/toggle-switch.js#L5), but I guess it's needs a proper API to read/set the value. You can find it in my branch: https://github.com/simurai/matte/tree/toggle-switch

![toggleswitch](https://f.cloud.github.com/assets/378023/649979/ceba6926-d451-11e2-8c1d-2e61f8e24f28.png)

---

It fits the radio and checkbox in size:
![compared](https://f.cloud.github.com/assets/378023/650065/b6e0c2da-d453-11e2-9f4a-a813bd896972.png)

---

You can easily customize the color like:

``` css
.myApp .matte-ToggleSwitch--on {
    background-color: hsl(204, 100%, 65%);
    border-color: hsl(204, 100%, 55%);
}
```

![colors](https://f.cloud.github.com/assets/378023/650083/3894bcd2-d454-11e2-913f-c16d3aed065b.png)

---

You can easily customize the size with just one property:

``` css
.myApp .matte-ToggleSwitch {
    font-size: 16px;
}
```

![sizes](https://f.cloud.github.com/assets/378023/650098/a35020d4-d454-11e2-965e-fb546e33cb64.png)
